# Generated by Django 4.1 on 2023-10-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
